//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSys.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int id { get; set; }
        public string branch1 { get; set; }
        public string branch2 { get; set; }
        public string branch3 { get; set; }
    }
}
