//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSys.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string data { get; set; }
        public System.DateTime date { get; set; }
        public int status { get; set; }
    }
}
