//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSys.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        public long id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
