//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSys.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string id { get; set; }
        public string name { get; set; }
        public int categories { get; set; }
        public string img_url { get; set; }
        public System.DateTime date { get; set; }
        public string summary { get; set; }
        public string contents { get; set; }
        public int view_count { get; set; }
        public int oder { get; set; }
        public int status { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
