//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSys.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poster
    {
        public int id { get; set; }
        public string image_url { get; set; }
        public string text { get; set; }
        public string company_name { get; set; }
        public int enable { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
